# Generated by Django 4.1.1 on 2022-10-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
    ]
