# Generated by Django 4.1.1 on 2022-10-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infotech', '0002_alter_form_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Lastname',
            new_name='lastname',
        ),
    ]
