# Generated by Django 4.1.1 on 2022-10-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infotech', '0003_rename_firstname_form_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Mobile',
            new_name='mobile',
        ),
    ]
